# Generated by Django 5.1 on 2024-08-23 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('connected_locations', models.ManyToManyField(blank=True, to='location.location')),
                ('general_actions', models.ManyToManyField(blank=True, related_name='locations', to='action.generalaction')),
                ('location_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='location.locationtype')),
            ],
        ),
    ]
