# Generated by Django 5.1 on 2024-08-23 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('asset', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(max_length=300)),
                ('price', models.PositiveIntegerField(default=1)),
                ('rarity', models.CharField(choices=[('standard', 'Standard'), ('rare', 'rare')], default='standart', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item.item')),
                ('affected_stat', models.CharField(choices=[('health', 'Health'), ('strength', 'Strength'), ('agility', 'Agility'), ('speed', 'Speed'), ('physical', 'Physical')], max_length=50)),
                ('value', models.IntegerField()),
                ('expire_in', models.PositiveIntegerField(default=5)),
            ],
            options={
                'abstract': False,
            },
            bases=('item.item',),
        ),
    ]
