# Generated by Django 5.1 on 2024-08-23 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0005_alter_item_options_item_polymorphic_ctype'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='FarmingAction',
            fields=[
                ('generalaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='action.generalaction')),
                ('reward_quantity', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('skill_updating', models.CharField(choices=[('wooding', 'Wooding'), ('mining', 'Mining'), ('picking', 'Picking'), ('searching', 'Searching')], max_length=30)),
                ('value_updating', models.IntegerField(default=1)),
                ('reward_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item')),
            ],
            bases=('action.generalaction',),
        ),
    ]
