# Generated by Django 5.1 on 2024-08-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmingaction',
            name='skill_updating',
            field=models.CharField(blank=True, choices=[('wooding', 'Wooding'), ('mining', 'Mining'), ('picking', 'Picking'), ('searching', 'Searching')], max_length=30, null=True),
        ),
    ]
